.PHONY: all 
all: fahrenheit_celsius.o celsius_fahrenheit.o
	./fahrenheit_celsius.o
	./celsius_fahrenheit.o

fahrenheit_celsius.o: fahrenheit_celsius.c
	cc -o fahrenheit_celsius.o fahrenheit_celsius.c

celsius_fahrenheit.o: celsius_fahrenheit.c
	cc -o celsius_fahrenheit.o celsius_fahrenheit.c
