all: first_file_copying.o \
	second_file_copying.o \
	first_count_characters.o \
	second_count_characters.o \
	line_counting.o \
	count_tabs.o \
	count_blanks.o \
	count_newlines.o

first_file_copying.o: first_file_copying.c
	cc -o first_file_copying.o first_file_copying.c

second_file_copying.o: second_file_copying.c
	cc -o second_file_copying.o second_file_copying.c

first_count_characters.o: first_count_characters.c
	cc -o first_count_characters.o first_count_characters.c

second_count_characters.o: second_count_characters.c
	cc -o second_count_characters.o second_count_characters.c

line_counting.o: line_counting.c
	cc -o line_counting.o line_counting.c

count_tabs.o: count_tabs.c
	cc -o count_tabs.o count_tabs.c

count_blanks.o: count_blanks.c
	cc -o count_blanks.o count_blanks.c
	
count_newlines.o: count_newlines.c
	cc -o count_newlines.o count_newlines.c
